#!/bin/bash
# Provision 5 merchant tenants, 2 users each, in the AnyCompanyPay Cognito pool.
# Each user: merchant group (role) + custom:merchant_id / custom:merchant_name (tenant).
# Idempotent-ish: skips create if the user already exists, still (re)sets attrs/password/group.
set -uo pipefail
# Region from the environment (never hardcoded).
R="${R:-${AWS_REGION:-${CDK_DEFAULT_REGION:-$(aws configure get region 2>/dev/null || echo us-west-2)}}}"
if [ -z "$R" ]; then
  echo "ERROR: no region. Set AWS_REGION (or R), e.g. AWS_REGION=us-west-2 $0" >&2; exit 1
fi
# Optional env discriminator. Empty by default → clean common names (no suffix).
ENV_NAME="${ENV_NAME:-}"
APP_STACK="AnyCompanyPayAppStack${ENV_NAME:+-${ENV_NAME}}"
# Target user pool: use POOL if given, otherwise DISCOVER it from the app stack
# output (AnyCompanyPayAppStack[-<env>] UserPoolId) — nothing pool-specific is hardcoded.
POOL="${POOL:-$(aws cloudformation describe-stacks --region "$R" --stack-name "$APP_STACK" \
  --query "Stacks[0].Outputs[?OutputKey=='UserPoolId'].OutputValue | [0]" --output text 2>/dev/null)}"
if [ -z "$POOL" ] || [ "$POOL" = "None" ]; then
  echo "ERROR: could not resolve the Cognito user pool. Set POOL=<id> or deploy $APP_STACK in $R first." >&2
  exit 1
fi
echo "Region: $R   Env: $ENV_NAME   Pool: $POOL"

# Shared demo password for the merchant users. GENERATED by Secrets Manager and
# stored there — never hardcoded, never printed. Re-runs reuse the existing
# secret so the password stays stable across invocations.
SECRET_ID="${SECRET_ID:-anycompany-pay${ENV_NAME:+/${ENV_NAME}}/cognito/merchants}"
PW="$(aws secretsmanager get-secret-value --region "$R" --secret-id "$SECRET_ID" \
  --query SecretString --output text 2>/dev/null | python3 -c \
  'import json,sys; s=sys.stdin.read().strip(); print(json.loads(s)["password"] if s else "")' 2>/dev/null || true)"
if [ -z "$PW" ]; then
  PW="$(aws secretsmanager get-random-password --region "$R" --password-length 20 \
    --require-each-included-type --exclude-punctuation \
    --query RandomPassword --output text)"
  if [ -z "$PW" ]; then echo "ERROR: could not generate a password." >&2; exit 1; fi
  aws secretsmanager create-secret --region "$R" --name "$SECRET_ID" \
    --description "Generated shared password for the demo merchant users" \
    --secret-string "{\"password\":\"$PW\"}" >/dev/null 2>/dev/null ||
  aws secretsmanager put-secret-value --region "$R" --secret-id "$SECRET_ID" \
    --secret-string "{\"password\":\"$PW\"}" >/dev/null
  echo "Generated a new merchant password and stored it in $SECRET_ID"
else
  echo "Reusing the merchant password already in $SECRET_ID"
fi

# merchant_id | merchant_name | user1 | user2
MERCHANTS=(
  "mch_luxe|Luxe Living|owner@luxeliving.example|ops@luxeliving.example"
  "mch_nova|NovaMart|owner@novamart.example|ops@novamart.example"
  "mch_pixel|PixelForge|owner@pixelforge.example|ops@pixelforge.example"
  "mch_terra|TerraFoods|owner@terrafoods.example|ops@terrafoods.example"
  "mch_volt|VoltCharge|owner@voltcharge.example|ops@voltcharge.example"
)

provision_user () {
  local email="$1" mid="$2" mname="$3"
  echo "  - $email  ($mid / $mname)"
  aws cognito-idp admin-create-user --region "$R" --user-pool-id "$POOL" \
    --username "$email" --message-action SUPPRESS \
    --user-attributes Name=email,Value="$email" Name=email_verified,Value=true \
      Name=custom:merchant_id,Value="$mid" Name=custom:merchant_name,Value="$mname" \
    >/dev/null 2>/tmp/cu.err || grep -q UsernameExistsException /tmp/cu.err || { echo "    create failed:"; cat /tmp/cu.err; return 1; }
  # Ensure attributes are set even if the user already existed.
  aws cognito-idp admin-update-user-attributes --region "$R" --user-pool-id "$POOL" \
    --username "$email" \
    --user-attributes Name=custom:merchant_id,Value="$mid" Name=custom:merchant_name,Value="$mname" \
    Name=email_verified,Value=true >/dev/null
  aws cognito-idp admin-set-user-password --region "$R" --user-pool-id "$POOL" \
    --username "$email" --password "$PW" --permanent >/dev/null
  aws cognito-idp admin-add-user-to-group --region "$R" --user-pool-id "$POOL" \
    --username "$email" --group-name merchant >/dev/null
}

for row in "${MERCHANTS[@]}"; do
  IFS='|' read -r MID MNAME U1 U2 <<< "$row"
  echo "Merchant: $MNAME ($MID)"
  provision_user "$U1" "$MID" "$MNAME"
  provision_user "$U2" "$MID" "$MNAME"
done

echo
echo "Password for all merchant users — fetch it with:"
echo "  aws secretsmanager get-secret-value --region $R --secret-id $SECRET_ID \\"
echo "    --query SecretString --output text"
echo
echo "=== Verify: merchant users with their tenant tag ==="
aws cognito-idp list-users --region "$R" --user-pool-id "$POOL" \
  --query "Users[?Attributes[?Name=='custom:merchant_id']].{email:Username,mid:Attributes[?Name=='custom:merchant_id']|[0].Value,mname:Attributes[?Name=='custom:merchant_name']|[0].Value,status:UserStatus}" \
  --output table
