#!/bin/bash
# Provision a Connect AGENT user who can answer merchant chats.
#
# NOTE (superseded): AnyCompanyPayConnectStack now creates `agent1` (and an admin user)
# during the stack deploy, with a Secrets Manager GENERATED password — no
# plaintext, no manual step. This script is kept only as a manual fallback / for
# ad-hoc extra agents. If you run it against an instance whose users the stack
# already manages, it will just update the existing user (DuplicateResource ->
# update), which is harmless. Prefer `cdk deploy AnyCompanyPayConnectStack-<env>`.
#
# The chat-answering infrastructure (support queue + Chat routing profile) is
# created by AnyCompanyPayConnectStack; this script only creates the user, so no
# password ever lands in the CloudFormation template. The user is assigned the
# stack's chat routing profile + the instance's default "Agent" security
# profile, and given a soft-phone config.
#
# Env overrides:
#   R          region (default: configured region / AWS_REGION)
#   ENV_NAME   environment discriminator (default v2)
#   ALIAS      Connect instance alias (default anycompany-pay-<account>-<env>)
#   RP_NAME    routing profile name (default anycompany-pay-chat-<env>)
#   AGENT      agent login (default agent1)
#   SECRET_ID  Secrets Manager id holding the generated agent password
#              (default anycompany-pay[/<env>]/connect/<agent>)
#   AGENT_EMAIL optional email
#
# The password is GENERATED by Secrets Manager and stored there — it is never
# hardcoded, never passed on the command line, and never printed.
set -uo pipefail
# Region from the environment (never hardcoded).
R="${R:-${AWS_REGION:-${CDK_DEFAULT_REGION:-$(aws configure get region 2>/dev/null || echo us-west-2)}}}"
if [ -z "$R" ]; then
  echo "ERROR: no region. Set AWS_REGION (or R), e.g. AWS_REGION=us-west-2 $0" >&2; exit 1
fi
# Optional env discriminator. Empty by default → clean common names (no suffix).
ENV_NAME="${ENV_NAME:-}"
ACCOUNT="$(aws sts get-caller-identity --query Account --output text)"
ALIAS="${ALIAS:-anycompany-pay-${ACCOUNT}${ENV_NAME:+-${ENV_NAME}}}"
RP_NAME="${RP_NAME:-anycompany-pay-chat${ENV_NAME:+-${ENV_NAME}}}"
AGENT="${AGENT:-agent1}"
AGENT_EMAIL="${AGENT_EMAIL:-}"

# Agent password: reuse the secret the Connect stack already generated for this
# user if it exists, otherwise generate one and store it. Same secret naming as
# AnyCompanyPayConnectStack so the stack and this fallback script agree.
SECRET_ID="${SECRET_ID:-anycompany-pay${ENV_NAME:+/${ENV_NAME}}/connect/${AGENT}}"
AGENT_PW="$(aws secretsmanager get-secret-value --region "$R" --secret-id "$SECRET_ID" \
  --query SecretString --output text 2>/dev/null | python3 -c \
  'import json,sys; s=sys.stdin.read().strip()
print("" if not s else (json.loads(s).get("password","") if s.startswith("{") else s))' 2>/dev/null || true)"
SECRET_CREATED=0
if [ -z "$AGENT_PW" ]; then
  # Connect requires at least one symbol, so keep punctuation in this one.
  AGENT_PW="$(aws secretsmanager get-random-password --region "$R" --password-length 20 \
    --require-each-included-type --exclude-characters '"@/\' \
    --query RandomPassword --output text)"
  if [ -z "$AGENT_PW" ]; then echo "ERROR: could not generate a password." >&2; exit 1; fi
  aws secretsmanager create-secret --region "$R" --name "$SECRET_ID" \
    --description "Generated password for Connect agent $AGENT" \
    --secret-string "{\"username\":\"$AGENT\",\"password\":\"$AGENT_PW\"}" >/dev/null 2>/dev/null ||
  aws secretsmanager put-secret-value --region "$R" --secret-id "$SECRET_ID" \
    --secret-string "{\"username\":\"$AGENT\",\"password\":\"$AGENT_PW\"}" >/dev/null
  SECRET_CREATED=1
fi

echo "Resolving Connect instance for alias: $ALIAS"
INSTANCE_ID="$(aws connect list-instances --region "$R" \
  --query "InstanceSummaryList[?InstanceAlias=='${ALIAS}'].Id | [0]" --output text)"
if [ -z "$INSTANCE_ID" ] || [ "$INSTANCE_ID" = "None" ]; then
  echo "ERROR: no Connect instance found for alias $ALIAS"; exit 1
fi
echo "  InstanceId: $INSTANCE_ID"

echo "Resolving routing profile: $RP_NAME"
RP_ID="$(aws connect list-routing-profiles --region "$R" --instance-id "$INSTANCE_ID" \
  --query "RoutingProfileSummaryList[?Name=='${RP_NAME}'].Id | [0]" --output text)"
if [ -z "$RP_ID" ] || [ "$RP_ID" = "None" ]; then
  echo "ERROR: routing profile '$RP_NAME' not found (deploy AnyCompanyPayConnectStack first)"; exit 1
fi
echo "  RoutingProfileId: $RP_ID"

echo "Resolving 'Agent' security profile"
SP_ID="$(aws connect list-security-profiles --region "$R" --instance-id "$INSTANCE_ID" \
  --query "SecurityProfileSummaryList[?Name=='Agent'].Id | [0]" --output text)"
if [ -z "$SP_ID" ] || [ "$SP_ID" = "None" ]; then
  echo "ERROR: default 'Agent' security profile not found"; exit 1
fi
echo "  SecurityProfileId: $SP_ID"

# Connect requires FirstName + LastName in IdentityInfo when creating a user.
if [ -n "$AGENT_EMAIL" ]; then
  IDENTITY="{\"FirstName\":\"AnyCompanyPay\",\"LastName\":\"Agent\",\"Email\":\"${AGENT_EMAIL}\"}"
else
  IDENTITY="{\"FirstName\":\"AnyCompanyPay\",\"LastName\":\"Agent\"}"
fi

echo "Creating agent user: $AGENT"
# NOTE: do NOT use $UID for the user id — UID is a readonly variable in bash.
EXISTED=0
if aws connect create-user --region "$R" --instance-id "$INSTANCE_ID" \
  --username "$AGENT" --password "$AGENT_PW" \
  --phone-config '{"PhoneType":"SOFT_PHONE","AutoAccept":false}' \
  --security-profile-ids "$SP_ID" \
  --routing-profile-id "$RP_ID" \
  --identity-info "$IDENTITY" \
  >/dev/null 2>/tmp/agent.err; then
  echo "  created."
elif grep -qiE 'DuplicateResourceException|already exists' /tmp/agent.err; then
  # Connect reports an existing user either as DuplicateResourceException or as
  # InvalidRequestException "A user with username ... already exists in your
  # directory" (depends on the instance's identity-management mode). Treat both
  # as idempotent: look up the existing user and converge its profiles.
  EXISTED=1
  echo "  user already exists — updating routing profile + security profile"
  AGENT_ID="$(aws connect list-users --region "$R" --instance-id "$INSTANCE_ID" \
    --query "UserSummaryList[?Username=='${AGENT}'].Id | [0]" --output text)"
  if [ -z "$AGENT_ID" ] || [ "$AGENT_ID" = "None" ]; then
    echo "  ERROR: user '$AGENT' exists but its Id could not be resolved:" >&2
    cat /tmp/agent.err >&2; exit 1
  fi
  aws connect update-user-routing-profile --region "$R" --instance-id "$INSTANCE_ID" \
    --user-id "$AGENT_ID" --routing-profile-id "$RP_ID" >/dev/null
  aws connect update-user-security-profiles --region "$R" --instance-id "$INSTANCE_ID" \
    --user-id "$AGENT_ID" --security-profile-ids "$SP_ID" >/dev/null
  echo "  updated existing user (password left unchanged)."
else
  echo "  create failed:" >&2; cat /tmp/agent.err >&2; exit 1
fi

echo
echo "=== Done ==="
if [ "$EXISTED" = "1" ]; then
  echo "Agent login : $AGENT (existing user — password NOT changed)"
else
  echo "Agent login : $AGENT"
fi
if [ "$SECRET_CREATED" = "1" ]; then
  echo "              password generated and stored in $SECRET_ID"
fi
echo "Password    : aws secretsmanager get-secret-value --region $R \\"
echo "                --secret-id $SECRET_ID --query SecretString --output text"
echo "CCP URL     : https://${ALIAS}.my.connect.aws/ccp-v2/"
echo "Sign in, set status to Available, and accept incoming chats."
